---
version: '3'

services:
  job-cluster-in-memory:
    build: .
    container_name: job-cluster-in-memory
    ports:
    - "8081:8081"
    - "9249:9249"
    volumes:
    - state-in-memory:/state
    command: standalone-job --job-classname com.apopova.filnk.orderbook_rebuilder.StreamingJob --job-id 00000000000000000000000000000000 --job-name "StreamingJob-InMemory" --checkpointing-interval-ms 90000
    environment:
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: job-cluster-in-memory
      jobmanager.memory.process.size: 1024m
      state.checkpoints.dir: file:///state-in-memory

  taskmanager-in-memory:
    build: .
    container_name: taskmanager-in-memory
    ports:
    - "9250:9249"
    volumes:
    - state-in-memory:/state
    command: taskmanager
    environment:
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: job-cluster-in-memory
      taskmanager.memory.process.size: 1024m
      state.checkpoints.dir: file:///state-in-memory

  job-cluster-rocks-db:
    build: .
    container_name: job-cluster-rocks-db
    ports:
      - "8082:8081"
      - "9251:9249"
    volumes:
      - state-rocks-db:/Users/anastasiyapopova/Documents/development/ob-rebuilder-rocks-db
    command: standalone-job --job-classname com.apopova.filnk.orderbook_rebuilder.StreamingJob --job-id 00000000000000000000000000000001 --job-name "StreamingJob-RocksDB" --checkpointing-interval-ms 90000
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: job-cluster-rocks-db
        jobmanager.memory.process.size: 3000m
        state.checkpoints.dir: file:///state-rocks-db

  taskmanager-rock-db:
    build: .
    container_name: taskmanager-rock-db
    ports:
      - "9252:9249"
    volumes:
      - state-rocks-db:/Users/anastasiyapopova/Documents/development/ob-rebuilder-rocks-db
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: job-cluster-rocks-db
        taskmanager.memory.process.size: 3000m
        state.backend: rocksdb
        state.checkpoints.dir: file:///state-rocks-db

  prometheus:
    image: prom/prometheus:v2.32.1
    container_name: prometheus
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus/flink.rules.yml:/etc/prometheus/flink.rules.yml

  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    ports:
    - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=flink
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning/

volumes:
  state-in-memory:
  state-rocks-db:
