---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
- flink.rules.yml

scrape_configs:
  - job_name: 'flink-in-memory'
    static_configs:
    - targets: ['job-cluster-in-memory:9249', 'taskmanager-in-memory:9249']
  - job_name: 'flink-rocks-db'
    static_configs:
      - targets: ['job-cluster-rocks-db:9249', 'taskmanager-rock-db:9249']
