{
 "title": "Flink",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "jobs", "query": { "query": "label_values(job_name)" } }
  ]
 },
 "panels": [
  { "title": "JobManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "heap memory [{{instance}}]"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "non-heap memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "GC Overhead",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(flink_jobmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[5m])/1000 + rate(flink_jobmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[5m])/1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Max",
     "legendFormat": "max non heap memory [{{instance}}]"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max",
     "legendFormat": "max heap memory [{{instance}}]"
    }
   ]
  },
  { "title": "TaskManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "heap memory [{{instance}}]"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "non-heap memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "GC Overhead",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[5m])/1000 + rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[5m])/1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Max",
     "legendFormat": "max non heap memory [{{instance}}]"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max",
     "legendFormat": "max heap memory [{{instance}}]"
    }
   ]
  },
  { "title": "StreamingJob", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Bytes in",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesInLocalPerSecond{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}_{{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesOutPerSecond{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}_{{task_name}}"
    }
   ]
  },
  {
   "title": "Records In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}_{{task_name}}"
    }
   ]
  },
  {
   "title": "Records out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}_{{task_name}}"
    }
   ]
  },
  {
   "title": "Min event processing time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_min_gauge{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Max event processing time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_max_gauge{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 70 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Full Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_fullRestarts{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointSize{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Number of failed checkpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Number of completed checkpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfCompletedCheckpoints{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Total number of checkpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_totalNumberOfCheckpoints{job_name=~\"$jobs\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  }
 ]
}